version: "3.7"

services:
  app:
    image: "gelugu/devops-for-programmers-project-lvl1"
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - "./app:/app"
    env_file:
      - ./app/.env.tests
    command: bash -c "npm ci && npm test"
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    env_file:
      - ./app/.env.tests
